### ISSUE TITLE
Add support for Modified AozoraEpub3

### ISSUE THREAD

**Issue by rogenobl** [rogenobl/narou#1]
改造版AozoraEpub3への対応を追加する
- originalとmodified判別方法
  - ファイルの存在
    - org: template/OPS/css/vertical_font.css
    - mod: template/item/style/font.css
- ~~フラグの設定~~
  - Narou.aozoraepub3_typeで判定
- 使用するテンプレートの選択
  - Narou.aozoraepub3_typeの返すハッシュによって設定

### テンプレート使用箇所
- Command::Init#rewrite_aozoraepub3_files
- NovelConverter.activate_dakuten_font_files
- NovelConverter.inactivate_dakuten_font_files

**Comment by rogenobl** [comment]
### Narou.aozoraepub3_type用設定案
```
org:
  type: :org
  name: AozoraEpub3 (元祖)
  exist: template/OPS/css/vertical_font.css
  tmpl:
    src:
      normal: vertical_font.css
      dakuten: vertical_font_with_dakuten.css
      font: DMincho.ttf
    dst:
      css: template/OPS/css_custom/vertical_font.css
      font: template/OPS/fonts/DMincho.ttf
```
